import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/general/NavBarComponent/NavBar";
import Footer from "@/components/general/FooterComponent/FooterComponent";

export const metadata: Metadata = {
  title: "Jornadas Interhospitalarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <head>
            {/*<link rel="stylesheet" href="Styles.css"/>*/}
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
          </head>
          <body>
              <NavBar/>
              {children}
              <Footer>
              </Footer>
          </body>
      </html>
  );
}
