import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/general/NavBarComponent/NavBar";
import Footer from "@/components/general/FooterComponent/FooterComponent";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Jornadas Interhospitalarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <head>
            {/*<link rel="stylesheet" href="Styles.css"/>*/}
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
          </head>
          <body>
              <SessionProvider>
                  <NavBar/>
                  {children}
                  <Footer></Footer>
              </SessionProvider>
          </body>
      </html>
  );
}
