import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/general/NavBarComponent/NavBar";
import Footer from "@/components/general/FooterComponent/FooterComponent";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        {/*<link rel="stylesheet" href="Styles.css"/>*/}
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
      <body>
      <NavBar/>

      {children}

      <Footer></Footer>

      </body>
      </html>
  );
}
